# Generated by Django 4.0.2 on 2022-05-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalizing_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='isDescriptionRaw',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Description Raw'),
        ),
        migrations.AddField(
            model_name='relation',
            name='isExplanationRaw',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Explanation Raw'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='area',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Philosophy', 'Philosophy'), ('Design', 'Design'), ('Art', 'Art'), ('Electrical Engineering', 'Electrical Engineering'), ('Software Engineering', 'Software Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Mechanical Engineering', 'Mehcanical Engineering'), ('Biology', 'Biology'), ('Chemestry', 'Chemestry'), ('Mathematics', 'Mathematics'), ('Literature', 'Literature'), ('Music', 'Music'), ('Law', 'Law'), ('Business', 'Business'), ('Economics', 'Economics'), ('Political Science', 'Political Science'), ('Arquitecture', 'Arquitecture'), ('Anthropology', 'Anthropology'), ('Medicine', 'Medicine'), ('Education', 'Education'), ('Psychology', 'Psycology'), ('Sports', 'Sports'), ('Neuroscience', 'Neuroscience'), ('Agriculture', 'Agriculture'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='domain',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Philosophy', 'Philosophy'), ('Design', 'Design'), ('Art', 'Art'), ('Electrical Engineering', 'Electrical Engineering'), ('Software Engineering', 'Software Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Mechanical Engineering', 'Mehcanical Engineering'), ('Biology', 'Biology'), ('Chemestry', 'Chemestry'), ('Mathematics', 'Mathematics'), ('Literature', 'Literature'), ('Music', 'Music'), ('Law', 'Law'), ('Business', 'Business'), ('Economics', 'Economics'), ('Political Science', 'Political Science'), ('Arquitecture', 'Arquitecture'), ('Anthropology', 'Anthropology'), ('Medicine', 'Medicine'), ('Education', 'Education'), ('Psychology', 'Psycology'), ('Sports', 'Sports'), ('Neuroscience', 'Neuroscience'), ('Agriculture', 'Agriculture'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Domain'),
        ),
    ]
